CREATE TABLE `employees` (
  `uid` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `department` VARCHAR(64) NULL DEFAULT NULL,
  `email` DATE NULL DEFAULT NULL,
  `phone` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`uid`)
);
