---
version: '3.4'

services:

  apache:
    working_dir: /app
    image: httpd:2.4.41-alpine
    restart: always
    depends_on:
      - db
    volumes:
      - ./apache/staticfiles:/usr/local/apache2/htdocs/
    ports:
      - 8081:80

  db:
    working_dir: /app
    image: mariadb:10.4.7
    restart: always
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: example-test

  adminer:
    image: adminer:4.7.3
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
    db-data:
