---
version: '3.2'

services:

  apache:
    working_dir: /app
    image: httpd:2.4.41-alpine
    restart: always
    depends_on:
      - db
      - redis
      - api
    volumes:
      - ./ui/dist:/usr/local/apache2/htdocs/
    ports:
      - 8081:80

  ui: &ui
    working_dir: /app
    build:
      context: ./ui
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - 8082:8082
    entrypoint:
      - npm
      - run
      - serve

  shui:
    <<: *ui
    entrypoint:
      - sh

  api: &api
    working_dir: /go/src/api/
    build:
      context: ./api
    restart: always
    volumes:
      - ./api:/go/src/api/
    depends_on:
      - postgres
      - redis
      - adminer
    ports:
      - 8080:8080
    entrypoint:
      - go
      - run
      - main.go

  shapi:
    <<: *api
    entrypoint:
      - bash

  redis:
    working_dir: /app
    image: redis:5.0.5-alpine
    restart: always

  postgres:
    image: postgres:11.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword

  adminer:
    image: adminer:4.7.3
    restart: always
    ports:
      - 8084:8080

volumes:
    db-data:
