---
version: '3.2'

services:

  apache:
    working_dir: /app
    image: httpd:2.4.41-alpine
    restart: always
    depends_on:
      - postgres
      - redis
      - api
    volumes:
      - ./ui/dist:/usr/local/apache2/htdocs/
    ports:
      - 8081:80

  ui: &ui
    working_dir: /app
    build:
      context: ./ui
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - 8082:8082
    entrypoint:
      - npm
      - run
      - serve

  shui:
    <<: *ui
    entrypoint:
      - sh

  api: &api
    working_dir: /go/src/api/
    build:
      context: ./api
    volumes:
      - ./api:/go/src/api/
    depends_on:
      - postgres
      - redis
      - pgweb
    ports:
      - 8080:8080
    entrypoint:
      - go
      - run
      - main.go

  shapi:
    <<: *api
    entrypoint:
      - bash

  ctpl:
    image: ikerry/ctpl:v0.1.5
    working_dir: /app
    volumes:
      - .:/app
      - "$HOME/.aws:/root/.aws"

  flyway:
    working_dir: /database
    image: boxfuse/flyway:5.2.4-alpine
    depends_on:
      - postgres
      - pgweb
    volumes:
      - ./database/migrations:/flyway/sql/migrations
      - ./database/data:/flyway/sql/data
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/company
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=mypassword
    command:
      - migrate

  redis:
    working_dir: /app
    image: redis:5.0.5-alpine
    restart: always

  postgres:
    image: postgres:10.9-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=company

  pgweb:
    image: sosedoff/pgweb:0.11.3
    restart: always
    ports:
      - 8084:8081
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@postgres:5432/company?sslmode=disable

  stackup:
    image: realestate/stackup:latest
    volumes:
      - "$HOME/.aws:/root/.aws"
      - ".:/app"
    working_dir: /app
    entrypoint: stackup
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2

  aws:
    image: mesosphere/aws-cli:1.14.5
    working_dir: /app
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
    volumes:
      - .:/app
      - $HOME/.aws:/root/.aws    

volumes:
  db-data:
