---
version: '3.6'

services:

  ui: &ui
    working_dir: /app
    build:
      context: ./ui
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - 8082:8082
    entrypoint:
      - npm
      - run
      - serve

  shui:
    <<: *ui
    entrypoint:
      - sh

  api: &api
    working_dir: /go/src/api/
    build:
      context: ./api
    restart: always
    volumes:
      - ./api:/go/src/api/
    depends_on:
      - db
      - redis
    ports:
      - 8081:8081
    entrypoint:
      - go
      - run
      - main.go

  shapi:
    <<: *api
    entrypoint:
      - bash

  redis:
    working_dir: /app
    image: redis:5.0.5-alpine
    restart: always

  db:
    working_dir: /app
    image: mariadb:10.4.7
    restart: always
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: example-test

  adminer:
    image: adminer:4.7.3
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
    db-data:
