apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aws-eks-cluster
  region: ap-southeast-2

vpc:
  id: "vpc-06848ae49be4090cb"
  cidr: "10.30.0.0/16"
  subnets:
    public:
      ap-southeast-2a:
        id: "subnet-00198a705a6aa2a18"
        cidr: "10.30.10.0/24"

      ap-southeast-2b:
        id: "subnet-0bb5d3526b08b0fc1"
        cidr: "10.30.20.0/24"

      ap-southeast-2c:
        id: "subnet-0a67df2c950971ec0"
        cidr: "10.30.30.0/24"

    private:
      ap-southeast-2a:
        id: "subnet-0a634daffd9ddc7cd"
        cidr: "10.30.11.0/24"

      ap-southeast-2b:
        id: "subnet-056293408b0b3abee"
        cidr: "10.30.21.0/24"

      ap-southeast-2c:
        id: "subnet-0e626530f9d2bb101"
        cidr: "10.30.31.0/24"

nodeGroups:
  - name: ng-private-a
    instanceType: t3.medium
    volumeSize: 20
    volumeType: gp2
    volumeEncrypted: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 8
    labels:
      zone: ap-southeast-2a
    privateNetworking: true
    availabilityZones: ["ap-southeast-2a"]
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        cloudWatch: true

  - name: ng-private-b
    instanceType: t3.medium
    volumeSize: 20
    volumeType: gp2
    volumeEncrypted: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 8
    labels:
      zone: ap-southeast-2b
    privateNetworking: true
    availabilityZones: ["ap-southeast-2b"]
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        cloudWatch: true


  - name: ng-private-c
    instanceType: t3.medium
    volumeSize: 20
    volumeType: gp2
    volumeEncrypted: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 8
    labels:
      zone: ap-southeast-2c
    privateNetworking: true
    availabilityZones: ["ap-southeast-2c"]
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        cloudWatch: true

  - name: ng-performance-instances
    instanceType: t3.large
    volumeSize: 20
    volumeType: gp2
    volumeEncrypted: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 8
    labels:
      zone: ap-southeast-2c
    taints:
      special: "true:NoSchedule"
    privateNetworking: true
    availabilityZones: ["ap-southeast-2c"]
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler
