AWSTemplateFormatVersion:  "2010-09-09"
Resources:
  KubeDemoRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: {{{ ecr.repo }}}
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPullOnly
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::693429498512:root
                - arn:aws:iam::967276157215:root
                - arn:aws:iam::428235295317:root
                - arn:aws:iam::850603229734:root
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
