FROM golang:1.13-rc-alpine3.10 AS builder

ENV GO111MODULE=on
WORKDIR /go/src/api/
RUN apk add --no-cache gcc musl-dev ca-certificates git bash make curl jq
COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 go build -o /api main.go

FROM scratch AS final
COPY --from=builder /api /api

EXPOSE 8081
ENTRYPOINT ["/api"]
